// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNMEdh7g40cFwvmc_q7zu_VC4N0FX_IM',
    appId: '1:881862241580:web:72cf0d461dcfb4aa7b1089',
    messagingSenderId: '881862241580',
    projectId: 'advanced-projs',
    authDomain: 'advanced-projs.firebaseapp.com',
    storageBucket: 'advanced-projs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE0OayNK0x0kVqxTqtEBKje2xAta3811o',
    appId: '1:881862241580:android:b387f7dff00b38747b1089',
    messagingSenderId: '881862241580',
    projectId: 'advanced-projs',
    storageBucket: 'advanced-projs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiEzoBaakqIKfzXsQruqS_PRrKxWH7hk',
    appId: '1:881862241580:ios:be5589972dca4bc97b1089',
    messagingSenderId: '881862241580',
    projectId: 'advanced-projs',
    storageBucket: 'advanced-projs.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMiEzoBaakqIKfzXsQruqS_PRrKxWH7hk',
    appId: '1:881862241580:ios:be5589972dca4bc97b1089',
    messagingSenderId: '881862241580',
    projectId: 'advanced-projs',
    storageBucket: 'advanced-projs.firebasestorage.app',
    iosBundleId: 'com.example.fcmNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNMEdh7g40cFwvmc_q7zu_VC4N0FX_IM',
    appId: '1:881862241580:web:956d01c89cd8b4177b1089',
    messagingSenderId: '881862241580',
    projectId: 'advanced-projs',
    authDomain: 'advanced-projs.firebaseapp.com',
    storageBucket: 'advanced-projs.firebasestorage.app',
  );
}
